/**
 * Author : Faruq
 * List Constant
 */

module.exports = {
    DEVICE_ACTIVE:1,
    DEVICE_NONACTIVE:0,
    DEVICE_PENDING:2,
    NORMAL_CONDITION:1,
    ABNORMAL_CONDITION:0,
    HEARTRATE_LOWER_LIMIT:60,
    HEARTRATE_UPPER_LIMIT:100,
    TEMPERATURE_LOWER_LIMIT:35,
    TEMPERATURE_UPPER_LIMIT:38,
    SPO_LOWER_LIMIT:95,
    SPO_UPPER_LIMIT:100,

  }